import pyautogui
import webbrowser as wb
import time
wb.open("youtube.com")
# time.sleep(10)
# for i in range(50):
#     pyautogui.press("r")
#     pyautogui.press("a")
#     pyautogui.press("n")
#     pyautogui.press("d")
#     pyautogui.press("i")
#     pyautogui.press("_")
#     pyautogui.press("a")
#     pyautogui.press("m")
#     pyautogui.press("i")
#     pyautogui.press("t")
    # pyautogui.press("a")
    # pyautogui.press("t")
    # pyautogui.press("h")
    # pyautogui.press("i")
    # pyautogui.press("i")
    # pyautogui.press("_")
    # pyautogui.press("a")
    # pyautogui.press("s")
    # pyautogui.press("s")
    # pyautogui.press("_")
    # pyautogui.press("h")
    # pyautogui.press("o")
    # pyautogui.press("l")
    # pyautogui.press("e")
    # pyautogui.press("")
    # pyautogui.press("")
    # pyautogui.press("enter")
    # pyautogui.press("bsdka u ")
    # pyautogui.press("enter")

    # pyautogui.press("fuck u ")
    # # pyautogui.press("enter")
    # pyautogui.press("fuck u ")
    # # pyautogui.press("enter")
    # pyautogui.press("*** ")
    # pyautogui.press("enter")
